export declare const StyledStatusConsole: any;
export declare const StyledResizable: any;
export declare const StyledWrapper: any;
export declare const StyledEmptyWrapper: any;
export declare const StyledTabsAndActionWrapper: any;
export declare const StyledTabs: any;
export declare const StyledCloseIcon: any;
export declare const StyledContainer: any;
export declare const StyledTab: any;
