import { CSSProperties, ReactNode } from 'react';
import { PopoverActions } from '../index.types';
export default function ({ id, secondary, elevation, style, onClick, onClose, highlight, tooltip, children, popover, popoverTitle, popoverActions, hasToolbar, hasDecoration, endSeparator, startSeparator, }: {
    id: string;
    secondary?: boolean;
    elevation?: number;
    style?: CSSProperties;
    onClick?: any;
    onClose?: any;
    highlight?: 'default' | 'primary' | 'secondary';
    tooltip?: ReactNode | string;
    children?: ReactNode;
    popover?: any;
    popoverTitle?: string;
    popoverActions?: PopoverActions;
    hasToolbar?: boolean;
    hasDecoration?: boolean;
    endSeparator?: boolean;
    startSeparator?: boolean;
}): JSX.Element;
